import type { INodeProperties } from 'n8n-workflow';

export const templateOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['template'],
			},
		},
		options: [
			{
				name: 'Send',
				value: 'send',
				description: 'Send a WhatsApp template message',
				action: 'Send a template message',
			},
		],
		default: 'send',
	},
];

export const templateFields: INodeProperties[] = [
	// Bot Selection
	{
		displayName: 'Bot Name or ID',
		name: 'botId',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getBots',
		},
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['template'],
				operation: ['send'],
			},
		},
		description: 'Select the bot to send the template from. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	// Template Selection
	{
		displayName: 'Template Name or ID',
		name: 'templateName',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getTemplates',
			loadOptionsDependsOn: ['botId'],
		},
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['template'],
				operation: ['send'],
			},
		},
		description: 'Select the approved template to send. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	// Phone Number
	{
		displayName: 'Phone Number',
		name: 'phoneNumber',
		type: 'string',
		required: true,
		default: '',
		placeholder: '5491123456789',
		displayOptions: {
			show: {
				resource: ['template'],
				operation: ['send'],
			},
		},
		description: 'Recipient phone number with country code (e.g., 5491123456789)',
	},
	// Template Components
	{
		displayName: 'Components',
		name: 'templateComponents',
		type: 'fixedCollection',
		typeOptions: {
			multipleValues: true,
		},
		default: {},
		placeholder: 'Add Component',
		displayOptions: {
			show: {
				resource: ['template'],
				operation: ['send'],
			},
		},
		options: [
			{
				displayName: 'Component',
				name: 'components',
				values: [
					// ========== BUTTON FIELDS ==========
					{
						displayName: 'Button Sub Type',
						name: 'buttonSubType',
						type: 'options',
						displayOptions: {
							show: {
								componentType: ['button'],
							},
						},
						options: [
							{
								name: 'Quick Reply',
								value: 'quick_reply',
							},
							{
								name: 'URL',
								value: 'url',
							},
						],
						default: 'quick_reply',
					},
					{
						displayName: 'Button Type',
						name: 'buttonType',
						type: 'options',
						displayOptions: {
							show: {
								componentType: ['button'],
							},
						},
						options: [
							{
								name: 'Text/Payload',
								value: 'text',
							},
							{
								name: 'URL Suffix',
								value: 'url',
							},
						],
						default: 'text',
						description: 'Type of button variable',
					},
					{
						displayName: 'Button Value',
						name: 'buttonValue',
						type: 'string',
						displayOptions: {
							show: {
								componentType: ['button'],
							},
						},
						default: '',
						description: 'Button payload or URL suffix value',
					},

					{
						displayName: 'Component Type',
						name: 'componentType',
						type: 'options',
						options: [
							{
								name: 'Header',
								value: 'header',
							},
							{
								name: 'Body Variables',
								value: 'body',
							},
							{
								name: 'Button',
								value: 'button',
							},
						],
						default: 'body',
						description: 'Type of template component',
					},

					// ========== HEADER FIELDS ==========
					{
						displayName: 'Filename',
						name: 'headerFilename',
						type: 'string',
						displayOptions: {
							show: {
								componentType: ['header'],
								headerType: ['document'],
							},
						},
						default: '',
						description: 'Filename for the document',
					},
					{
						displayName: 'Header Type',
						name: 'headerType',
						type: 'options',
						displayOptions: {
							show: {
								componentType: ['header'],
							},
						},
						options: [
							{
								name: 'Text',
								value: 'text',
							},
							{
								name: 'Image',
								value: 'image',
							},
							{
								name: 'Video',
								value: 'video',
							},
							{
								name: 'Document',
								value: 'document',
							},
						],
						default: 'text',
						description: 'Type of header content',
					},
					{
						displayName: 'Text',
						name: 'headerText',
						type: 'string',
						displayOptions: {
							show: {
								componentType: ['header'],
								headerType: ['text'],
							},
						},
						default: '',
						description: 'Header text value',
					},
					{
						displayName: 'URL',
						name: 'headerUrl',
						type: 'string',
						displayOptions: {
							show: {
								componentType: ['header'],
								headerType: ['image', 'video', 'document'],
							},
						},
						default: '',
						description: 'URL of the media file',
					},

					// ========== BODY VARIABLES (NESTED) ==========
					{
						displayName: 'Variables',
						name: 'bodyVariables',
						type: 'fixedCollection',
						typeOptions: {
							multipleValues: true,
						},
						displayOptions: {
							show: {
								componentType: ['body'],
							},
						},
						default: {},
						placeholder: 'Add Variable',
						options: [
							{
								displayName: 'Variable',
								name: 'variables',
								values: [
									{
										displayName: 'Amount (X1000)',
										name: 'amount',
										type: 'number',
										displayOptions: {
											show: {
												type: ['currency'],
											},
										},
										default: 0,
										description: 'Amount in 1/1000 of currency unit (e.g., 100000 = $100.00)',
									},
									{
										displayName: 'Currency Code',
										name: 'currencyCode',
										type: 'options',
										displayOptions: {
											show: {
												type: ['currency'],
											},
										},
										options: [
											{ name: 'AED - UAE Dirham', value: 'AED' },
											{ name: 'AFN - Afghani', value: 'AFN' },
											{ name: 'ALL - Lek', value: 'ALL' },
											{ name: 'AMD - Armenian Dram', value: 'AMD' },
											{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
											{ name: 'AOA - Kwanza', value: 'AOA' },
											{ name: 'ARS - Argentine Peso', value: 'ARS' },
											{ name: 'AUD - Australian Dollar', value: 'AUD' },
											{ name: 'AWG - Aruban Florin', value: 'AWG' },
											{ name: 'AZN - Azerbaijan Manat', value: 'AZN' },
											{ name: 'BAM - Convertible Mark', value: 'BAM' },
											{ name: 'BBD - Barbados Dollar', value: 'BBD' },
											{ name: 'BDT - Taka', value: 'BDT' },
											{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
											{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
											{ name: 'BIF - Burundi Franc', value: 'BIF' },
											{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
											{ name: 'BND - Brunei Dollar', value: 'BND' },
											{ name: 'BOB - Boliviano', value: 'BOB' },
											{ name: 'BOV - Mvdol', value: 'BOV' },
											{ name: 'BRL - Brazilian Real', value: 'BRL' },
											{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
											{ name: 'BTN - Ngultrum', value: 'BTN' },
											{ name: 'BWP - Pula', value: 'BWP' },
											{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
											{ name: 'BZD - Belize Dollar', value: 'BZD' },
											{ name: 'CAD - Canadian Dollar', value: 'CAD' },
											{ name: 'CDF - Congolese Franc', value: 'CDF' },
											{ name: 'CHE - WIR Euro', value: 'CHE' },
											{ name: 'CHF - Swiss Franc', value: 'CHF' },
											{ name: 'CHW - WIR Franc', value: 'CHW' },
										{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
											{ name: 'CLP - Chilean Peso', value: 'CLP' },
											{ name: 'CNY - Yuan Renminbi', value: 'CNY' },
											{ name: 'COP - Colombian Peso', value: 'COP' },
										{ name: 'COU - Unidad De Valor Real', value: 'COU' },
											{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
											{ name: 'CUC - Peso Convertible', value: 'CUC' },
											{ name: 'CUP - Cuban Peso', value: 'CUP' },
											{ name: 'CVE - Cabo Verde Escudo', value: 'CVE' },
											{ name: 'CZK - Czech Koruna', value: 'CZK' },
											{ name: 'DJF - Djibouti Franc', value: 'DJF' },
											{ name: 'DKK - Danish Krone', value: 'DKK' },
											{ name: 'DOP - Dominican Peso', value: 'DOP' },
											{ name: 'DZD - Algerian Dinar', value: 'DZD' },
											{ name: 'EGP - Egyptian Pound', value: 'EGP' },
											{ name: 'ERN - Nakfa', value: 'ERN' },
											{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
											{ name: 'EUR - Euro', value: 'EUR' },
											{ name: 'FJD - Fiji Dollar', value: 'FJD' },
											{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
											{ name: 'GBP - Pound Sterling', value: 'GBP' },
											{ name: 'GEL - Lari', value: 'GEL' },
											{ name: 'GHS - Ghana Cedi', value: 'GHS' },
											{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
											{ name: 'GMD - Dalasi', value: 'GMD' },
											{ name: 'GNF - Guinean Franc', value: 'GNF' },
											{ name: 'GTQ - Quetzal', value: 'GTQ' },
											{ name: 'GYD - Guyana Dollar', value: 'GYD' },
											{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
											{ name: 'HNL - Lempira', value: 'HNL' },
											{ name: 'HRK - Kuna', value: 'HRK' },
											{ name: 'HTG - Gourde', value: 'HTG' },
											{ name: 'HUF - Forint', value: 'HUF' },
											{ name: 'IDR - Rupiah', value: 'IDR' },
											{ name: 'ILS - New Israeli Sheqel', value: 'ILS' },
											{ name: 'INR - Indian Rupee', value: 'INR' },
											{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
											{ name: 'IRR - Iranian Rial', value: 'IRR' },
											{ name: 'ISK - Iceland Krona', value: 'ISK' },
											{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
											{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
											{ name: 'JPY - Yen', value: 'JPY' },
											{ name: 'KES - Kenyan Shilling', value: 'KES' },
											{ name: 'KGS - Som', value: 'KGS' },
											{ name: 'KHR - Riel', value: 'KHR' },
											{ name: 'KMF - Comorian Franc', value: 'KMF' },
											{ name: 'KPW - North Korean Won', value: 'KPW' },
											{ name: 'KRW - Won', value: 'KRW' },
											{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
											{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
											{ name: 'KZT - Tenge', value: 'KZT' },
											{ name: 'LAK - Lao Kip', value: 'LAK' },
											{ name: 'LBP - Lebanese Pound', value: 'LBP' },
											{ name: 'LKR - Sri Lanka Rupee', value: 'LKR' },
											{ name: 'LRD - Liberian Dollar', value: 'LRD' },
											{ name: 'LSL - Loti', value: 'LSL' },
											{ name: 'LYD - Libyan Dinar', value: 'LYD' },
											{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
											{ name: 'MDL - Moldovan Leu', value: 'MDL' },
											{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
											{ name: 'MKD - Denar', value: 'MKD' },
											{ name: 'MMK - Kyat', value: 'MMK' },
											{ name: 'MNT - Tugrik', value: 'MNT' },
											{ name: 'MOP - Pataca', value: 'MOP' },
											{ name: 'MRU - Ouguiya', value: 'MRU' },
											{ name: 'MUR - Mauritius Rupee', value: 'MUR' },
											{ name: 'MVR - Rufiyaa', value: 'MVR' },
											{ name: 'MWK - Malawi Kwacha', value: 'MWK' },
											{ name: 'MXN - Mexican Peso', value: 'MXN' },
										{ name: 'MXV - Mexican Unidad De Inversion (UDI)', value: 'MXV' },
											{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
											{ name: 'MZN - Mozambique Metical', value: 'MZN' },
											{ name: 'NAD - Namibia Dollar', value: 'NAD' },
											{ name: 'NGN - Naira', value: 'NGN' },
											{ name: 'NIO - Cordoba Oro', value: 'NIO' },
											{ name: 'NOK - Norwegian Krone', value: 'NOK' },
											{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
											{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
											{ name: 'OMR - Rial Omani', value: 'OMR' },
											{ name: 'PAB - Balboa', value: 'PAB' },
											{ name: 'PEN - Sol', value: 'PEN' },
											{ name: 'PGK - Kina', value: 'PGK' },
											{ name: 'PHP - Philippine Peso', value: 'PHP' },
											{ name: 'PKR - Pakistan Rupee', value: 'PKR' },
											{ name: 'PLN - Zloty', value: 'PLN' },
											{ name: 'PYG - Guarani', value: 'PYG' },
											{ name: 'QAR - Qatari Rial', value: 'QAR' },
											{ name: 'RON - Romanian Leu', value: 'RON' },
											{ name: 'RSD - Serbian Dinar', value: 'RSD' },
											{ name: 'RUB - Russian Ruble', value: 'RUB' },
											{ name: 'RWF - Rwanda Franc', value: 'RWF' },
											{ name: 'SAR - Saudi Riyal', value: 'SAR' },
											{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
											{ name: 'SCR - Seychelles Rupee', value: 'SCR' },
											{ name: 'SDG - Sudanese Pound', value: 'SDG' },
											{ name: 'SEK - Swedish Krona', value: 'SEK' },
											{ name: 'SGD - Singapore Dollar', value: 'SGD' },
											{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
											{ name: 'SLL - Leone', value: 'SLL' },
											{ name: 'SOS - Somali Shilling', value: 'SOS' },
											{ name: 'SRD - Surinam Dollar', value: 'SRD' },
											{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
											{ name: 'STN - Dobra', value: 'STN' },
											{ name: 'SVC - El Salvador Colon', value: 'SVC' },
											{ name: 'SYP - Syrian Pound', value: 'SYP' },
											{ name: 'SZL - Lilangeni', value: 'SZL' },
											{ name: 'THB - Baht', value: 'THB' },
											{ name: 'TJS - Somoni', value: 'TJS' },
											{ name: 'TMT - Turkmenistan New Manat', value: 'TMT' },
											{ name: 'TND - Tunisian Dinar', value: 'TND' },
											{ name: 'TOP - Pa\'anga', value: 'TOP' },
											{ name: 'TRY - Turkish Lira', value: 'TRY' },
											{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
											{ name: 'TWD - New Taiwan Dollar', value: 'TWD' },
											{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
											{ name: 'UAH - Hryvnia', value: 'UAH' },
											{ name: 'UGX - Uganda Shilling', value: 'UGX' },
											{ name: 'USD - US Dollar', value: 'USD' },
										{ name: 'USN - US Dollar (Next Day)', value: 'USN' },
											{ name: 'UYI - Uruguay Peso en Unidades Indexadas (UI)', value: 'UYI' },
											{ name: 'UYU - Peso Uruguayo', value: 'UYU' },
											{ name: 'UYW - Unidad Previsional', value: 'UYW' },
											{ name: 'UZS - Uzbekistan Sum', value: 'UZS' },
											{ name: 'VES - Bolívar Soberano', value: 'VES' },
											{ name: 'VND - Dong', value: 'VND' },
											{ name: 'VUV - Vatu', value: 'VUV' },
											{ name: 'WST - Tala', value: 'WST' },
											{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
											{ name: 'XAG - Silver', value: 'XAG' },
											{ name: 'XAU - Gold', value: 'XAU' },
											{ name: 'XBA - Bond Markets Unit European Composite Unit (EURCO)', value: 'XBA' },
											{ name: 'XBB - Bond Markets Unit European Monetary Unit (E.M.U.-6)', value: 'XBB' },
											{ name: 'XBC - Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', value: 'XBC' },
											{ name: 'XBD - Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', value: 'XBD' },
											{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
											{ name: 'XDR - SDR (Special Drawing Right)', value: 'XDR' },
											{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
											{ name: 'XPD - Palladium', value: 'XPD' },
											{ name: 'XPF - CFP Franc', value: 'XPF' },
											{ name: 'XPT - Platinum', value: 'XPT' },
											{ name: 'XSU - Sucre', value: 'XSU' },
										{ name: 'XTS - Codes Specifically Reserved For Testing Purposes', value: 'XTS' },
											{ name: 'XUA - ADB Unit of Account', value: 'XUA' },
										{ name: 'XXX - The Codes Assigned For Transactions Where No Currency Is Involved', value: 'XXX' },
											{ name: 'YER - Yemeni Rial', value: 'YER' },
											{ name: 'ZAR - Rand', value: 'ZAR' },
											{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
											{ name: 'ZWL - Zimbabwe Dollar', value: 'ZWL' },
										],
										default: 'USD',
										description: 'ISO 4217 currency code',
									},
									{
										displayName: 'Fallback Value',
										name: 'fallback',
										type: 'string',
										displayOptions: {
											show: {
												type: ['currency'],
											},
										},
										default: '',
										description: 'Fallback display value',
									},
									{
										displayName: 'Value',
										name: 'value',
										type: 'string',
										displayOptions: {
											show: {
												type: ['text', 'date_time'],
											},
										},
										default: '',
										description: 'Variable value (can use expressions like {{ $JSON.field }})',
									},
									{
										displayName: 'Variable Type',
										name: 'type',
										type: 'options',
										options: [
											{
												name: 'Text',
												value: 'text',
											},
											{
												name: 'Currency',
												value: 'currency',
											},
											{
												name: 'Date/Time',
												value: 'date_time',
											},
										],
										default: 'text',
										description: 'Type of body variable',
									},
								],
							},
						],
						description: 'Body variables for the template',
					},
				],
			},
		],
		description: 'Template components (header, body variables, buttons)',
	},
];
